# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-mongodb-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-mongodb
    source:
      repo: https://github.com/SRT-ISV/terraform-google-mongodb.git
      sourceType: git
  ui:
    input:
      variables:
        atlas_org_id:
          name: atlas_org_id
          title: Atlas Org Id
        atlas_private_key_secret:
          name: atlas_private_key_secret
          title: Atlas Private Key Secret
        atlas_project_name:
          name: atlas_project_name
          title: Atlas Project Name
        atlas_public_key_secret:
          name: atlas_public_key_secret
          title: Atlas Public Key Secret
        atlas_region:
          name: atlas_region
          title: Atlas Region
        cluster_name:
          name: cluster_name
          title: Cluster Name
        database_password_secret:
          name: database_password_secret
          title: Database Password Secret
        gcp_project_id:
          name: project_id
          title: Gcp Project Id
        gcp_region:
          name: region
          title: Gcp Region
        gcp_zone:
          name: zone
          title: Gcp Zone
        instance_size:
          name: instance_size
          title: Instance Size
        mongo_db_major_version:
          name: mongo_db_major_version
          title: Mongo Db Major Version
        network_whitelist:
          name: network_whitelist
          title: Network Whitelist
        suffix:
          name: suffix
          title: Suffix
        user_invite_list:
          name: user_invite_list
          title: User Invite List
